# Generated by Django 2.2.1 on 2019-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190510_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='thumbnail_url',
            field=models.CharField(max_length=50),
        ),
    ]
