# Generated by Django 2.2.1 on 2019-05-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('thumbnail_url', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Guides',
            },
        ),
    ]
