# Generated by Django 2.2.1 on 2019-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragonia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('thumbnail_url', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Home Sections',
            },
        ),
    ]
