# Generated by Django 2.2.1 on 2019-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragonia', '0002_homesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='align',
            field=models.CharField(default='right', max_length=5),
            preserve_default=False,
        ),
    ]
